java.sql.SQLException: Could not open client transport with JDBC Uri: jdbc:hive2://x01sadaapp7a.vsi.uat.dbs.com:10000/default;ssl=true;sslTrustStore=/var/tmp/cacerts;trustStorePassword=changeit;principal=hive/_HOST@SVCSUAT.DBS.COM: null
        at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:215)
        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:163)
        at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at com.atscale.engine.hive1Jdbc.Hive1Connection.$anonfun$getNewConnection$1(Hive1Connection.scala:52)
        at com.atscale.engine.api.jdbc.JdbcConnection$.withAlternateClassLoaderContext(JdbcConnection.scala:131)
        at com.atscale.engine.hive1Jdbc.Hive1Connection.getNewConnection(Hive1Connection.scala:50)
        at com.atscale.engine.api.jdbc.JdbcConnection.newConnection(JdbcConnection.scala:57)
        at com.atscale.engine.api.jdbc.JdbcConnection.newConnection(JdbcConnection.scala:61)
        at com.atscale.engine.connection.groups.ConnectionTester$.$anonfun$testSubgroup$6(ConnectionTester.scala:127)
        at com.atscale.engine.connection.groups.ConnectionTester$.testConnection$1(ConnectionTester.scala:79)
        at com.atscale.engine.connection.groups.ConnectionTester$.$anonfun$testSubgroup$5(ConnectionTester.scala:127)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: null
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
        at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:182)
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:258)
        at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:52)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:49)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49)
        at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:190)
        ... 22 common frames omitted
2018-06-12 09:30:38,521 DEBUG [pool-2-thread-5] {} com.atscale.engine.thrift                - A Thrift TCP connection terminated without sending any data. This is normal behavior from some monitoring services.
2018-06-12 09:30:39,008 DEBUG [pool-2-thread-5] {} com.atscale.engine.thrift                - A Thrift TCP connection terminated without sending any data. This is normal behavior from some monitoring services.
